# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: grader_db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306" # Changed this line to use MYSQL_PORT
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks:
      - grader_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: grader_myadmin
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - grader_net

networks:
  grader_net:
    driver: bridge